services:
  db:
    build:
      context: ./DB
    # 自動で起動する
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - ./DB/basic_db:/src
    environment:
      - MSSQL_SA_PASSWORD=P@sswordP@ssword
      - DB_NAME=basic_db
      - PROJECT_PATH=/src/basic_db.sqlproj
      - DACPAC_PATH=/src/bin/debug/basic_db.dacpac
  api:
    build:
      context: ./API
      # dotnet watchはdotnet/sdk:8.0に含まれるので、ビルド環境ステージのイメージを利用する
      target: build-env
    volumes:
      - ./API:/api_src/
      # objは名前付きボリュームにする。こうすることでコンテナ内でdotnet restoreする際にこっちに影響を与えなくなる。
      - ignores:/api_src/Server/obj/
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
      - PEPPER=pepper
      - DB_CONNECTION_STR=Data Source=db, 1433;Initial Catalog=basic_db;User ID=sa;Password=P@sswordP@ssword;TrustServerCertificate=true;
    command: dotnet watch run --project /api_src/Server/Server.csproj --launch-profile http
volumes:
  ignores:
